### ISSUE TITLE
Great idea. 

### ISSUE THREAD

**Issue by vespertilian** [studds/nx-aws#46]
Hey, 

Thanks for creating this project. 

Exploring lots of different serverless options currently. 
Do you have any sample apps using nx-aws? 
Also do you have an opinion on SAM vs Serverless?  

Thanks again!

**Comment by studds** [comment]
Hey @vespertilian 

Here's a simple example app: https://github.com/studds/nx-aws-example

Let me know if you have any questions about any features or your particular use case.

### SAM vs Serverless

Do I have opinions? Why yes indeed, thank you for asking.

I've only used Serverless briefly, when I was similarly assessing the different options. In my opinion, Serverless is better in almost every way, except for one fatal flaw. I love that it's in node native, it makes things really easy to get started, the dev server is much more responsive (albeit at the cost of not faithfully simulating the Lambda environment), and it's got a great plugin ecosystem. For me though, it's a non-started: as near as I could tell, you have to rebuild your app for each environment you want to deploy it in. That's a deal-breaker for me. My workflow is to build once, and deploy as many times as required (eg. QA, Staging, Blue, Green).

**Comment by vespertilian** [comment]
Hey,

Wow, thanks for the quick reply! Your opinions are super helpful. I will be looking into the example tomorrow. It's late in Australia right now.

One more thing I am wondering is do you use Cognito? And do you like it? I hear mixed reviews.

**Comment by studds** [comment]
Where are you in Aus? I'm in Melbourne. Trying to squeeze in responses between work and my new lockdown childcare responsibilities!

I have used Cognito but I haven't configured any other auth providers, so I can't really compare. There are definitely some things that I found difficult or annoying (eg. being unable to issue a token with claims based on information available at time of login, other than scopes), but it's cheap, mostly fairly flexible, and tightly integrated with AWS. I'd hazard to say it's a steeper learning curve than other options. So if engineering time is at a premium, probably best to go with an option that's going to let you get up and running asap.

Alternatively, different take on the same goal, have you looked at [AWS Amplify](https://aws.amazon.com/amplify/)? It lets you get up and running super fast, including auth using cognito. I don't use it myself because I like to have a bit more direct control, but how many bad engineering decisions have been made by people who prefer to have a bit more direct control? In terms of bang for engineering hour, it's definitely worth a look. IMO, nx-aws is better as you have multiple apps or a complex architecture. Amplify is great if you've got a single DB / API / SPA.

**Comment by vespertilian** [comment]
Hey, 

I'm in Sydney. Sucks you guys are in lockdown again, I was talking to my friend on the weekend when he was out for his 1 hour of shopping. Thanks for finding the time to create the repository and answering my questions. All my friends with kids say that it's especially hard.

A very useful perspective on Cognito. Engineering time is always at a premium :).

I did look at Amplify but like you said I think you lose control. I hear it's really easy until it's not and then you are pulling your hair out trying to get it to play nice with other features.

I would love a 20-minute phone chat with you if you would indulge me. Your stack is looking very much like what I want, and you have a wallaby.js file (I am a big fan). I could buy you a coffee? Or promise to help contribute to your documentation. If you are open to the chat, vespertilian@gmail.com is my email and we could work out a time.

**Comment by studds** [comment]
Was good chatting with you this evening, and to get your feedback.

### Couple of quick fixes:

The bucket name collision in the example repo: https://github.com/studds/nx-aws-example/issues/1 
Failure to pick up region from ~/.aws/config: #48  (fixed in 0.7.1)

### And a couple of not-so-quick things:

Schematics: #47 (will take a bit more time, but I do want to add them)
Adding a stack name prefix option: #49 (won't take as much time, but didn't think 9.20 on a Tuesday was the right time to start).

**Comment by vespertilian** [comment]
Great chatting with you as well.

I really appreciate thoughts on AWS serverless tech stacks! I will likely
be in touch again :)
