### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by vespertilian** [studds/nx-aws#51]
Quick note I added a PR for windows support. Not sure if you got a notification about it so I thought I would leave a message here. 

Thanks

**Comment by studds** [comment]
Hey @vespertilian, thanks! I’ll have a look tomorrow!

**Comment by studds** [comment]
This looks good, though I've only tested briefly (because I'm not releasing it on the main branch right now). I've re-applied this change in 58d2afd on the https://github.com/studds/nx-aws/tree/schematics branch, which is the future of this project - mainly about adding schematics, but also other things. I've published this as 0.8.3 with the `next` tag on npm, you can install it using: `npm install --save-dev @nx-aws/core@next @nx-aws/sam@next @nx-aws/s3@next`.

If you can test it out and if further changes are required, raise a PR against the schematics branch? To test locally, I usually run `npm run build && npm run pack` and then in my project directory run (for example) `npm install /Users/me/code/nx-aws/nx-aws-core-0.8.1.tgz /Users/me/code/nx-aws/nx-aws-sam-0.8.1.tgz /Users/me/code/nx-aws/nx-aws-s3-0.8.1.tgz`. (In theory it should be possible to link to the compiled code, rather than packing first, but I haven't been able to get it working and I didn't spend too much time on it.)

**Comment by vespertilian** [comment]
Thanks for this will be testing it tomorrow. !

**Comment by vespertilian** [comment]
The next branch has been working for me (on mac) and my colleague on windows. Seems like you already pulled this into the schematics branch, thanks!

**Comment by studds** [comment]
Great, glad it's working :-)
